### ISSUE TITLE
TooManyRequestsException: Rate Exceeded.

### ISSUE THREAD

**Issue by danielstevenberger** [sst/ion#1099]
When enabling the warm config with a value of 20. I often get this error when deploying. It will also temporally cause the website to return TooManyRequestsException: Rate Exceeded as well. 

```
  MyWeb sst:aws:Nextjs → MyWebPrewarm aws:lambda:Invocation
   invoking Lambda Function (MyWebWarmerHandlerFunction): {"errorType":"TooManyRequestsException","errorMessage":"Rate Exceeded.","trace":["TooManyRequestsException: Rate Exceeded.","    at G (file:///var/task/index.mjs:51:174698)","    at uye (file:///var/task/index.mjs:51:128580)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async file:///var/task/index.mjs:13:38951","    at async file:///var/task/index.mjs:13:4524","    at async file:///var/task/index.mjs:21:15654","    at async file:///var/task/index.mjs:2:17360","    at async Promise.all (index 6)","    at async t1e (file:///var/task/index.mjs:51:285163)"]}
```

**Comment by jayair** [comment]
Just doing a search

https://stackoverflow.com/questions/36826352/aws-lambda-toomanyrequestsexception-rate-exceeded

**Comment by harrycollin** [comment]
I've also encountered this issue with defaults using the next.js construct.
