### ISSUE TITLE
ERR_REQUIRE_ESM when trying to start sst with `sst dev`

### ISSUE THREAD

**Issue by AlessandroVol23** [sst/ion#115]
After starting SST with `sst dev` I get the following error:

```
|  Error       
|  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/string-width/index.js from /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js not supported.
|  Instead change the require of index.js in /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
|      at Object.<anonymous> (/Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js:2:19) {
|    code: 'ERR_REQUIRE_ESM'
|  }

×  Failed
   Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/string-width/index.js from /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js not supported.
   Instead change the require of index.js in /Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/Users/alessandrovolpicella/repo/sfn-wait-callback-ion/.sst/platform/node_modules/wide-align/align.js:2:19) {
     code: 'ERR_REQUIRE_ESM'
   }
```

`sst.config.ts`

```ts
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "sfn-wait-callback-ion",
      removal: input?.stage === "prod" ? "retain" : "remove",
      home: "aws",
    };
  },

  async run() {
    new sst.aws.Nextjs("Frontend", {
      path: "packages/frontend",
    });
  },
});

```

node: 20.12.0
SST/ION: 0.0.224

**Comment by thdxr** [comment]
if you initialize a fresh nextjs project do you get the same issue?

**Comment by frankieramirez** [comment]
I get this error in my Github action when it tries to `sst deploy` but I don't see it when I deploy locally

**Comment by AlessandroVol23** [comment]
> if you initialize a fresh nextjs project do you get the same issue?

No then it works if I use drop-in mode

**Comment by gyeongmin-lee** [comment]
I got this error locally using `Remix` component as well, and resolved it by removing the `.sst/platform` folder and running `npm run dev` again.

**Comment by thdxr** [comment]
this should be fixed in 0.0.231 but if it happens again feel free to reopen

**Comment by vinodronold** [comment]
> removing the `.sst/platform` folder and running

Got the same issue, on ion 0.0.237... removing the `.sst/platform` folder and running `npm run dev` worked for me.

**Comment by jayair** [comment]
Hmm, can you post here if it happens again?
