### ISSUE TITLE
Init SST with Remix fails with unexpected error

### ISSUE THREAD

**Issue by eivindgi** [sst/ion#1217]
Following the example from the docs: https://sst.dev/docs/start/aws/remix

Running the following commands (from the docs):
```
❯ npx create-remix@latest

 remix   v2.12.1 💿 Let's build a better website...

   dir   Where should we create your new project?
         aws-remix

      ◼  Using basic template See https://remix.run/guides/templates for more
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

      ✔  Dependencies installed

      ✔  Git initialized

  done   That's it!

         Enter your project directory using cd ./aws-remix
         Check out README.md for development and deploy instructions.

         Join the community at https://rmx.as/discord

❯ cd aws-remix
❯ npx sst@latest init

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║   
   ╚════██║╚════██║   ██║   
   ███████║███████║   ██║   
   ╚══════╝╚══════╝   ╚═╝   

>  Remix detected. This will...
   - create an sst.config.ts
   - add sst to package.json

  Template: remix

⠧  Installing providers...✕  Unexpected error occurred. Please check the logs in .sst/log/sst.log
```
However there are no `.sst/log` folder

A `sst.config.ts`-file was created and looks like this:

```
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "budget-bear-web",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    new sst.aws.Remix("MyWeb");
  },
});
```
...with several problems:
```
❯ npm run typecheck

> typecheck
> tsc

sst.config.ts:1:22 - error TS6053: File '/Users/eivind/IdeaProjects/private/aws-remix/.sst/platform/config.d.ts' not found.

1 /// <reference path="./.sst/platform/config.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

sst.config.ts:3:16 - error TS2304: Cannot find name '$config'.

3 export default $config({
                 ~~~~~~~

sst.config.ts:4:7 - error TS7006: Parameter 'input' implicitly has an 'any' type.

4   app(input) {
        ~~~~~

sst.config.ts:12:9 - error TS2304: Cannot find name 'sst'.

12     new sst.aws.Remix("MyWeb");
           ~~~


Found 4 errors in the same file, starting at: sst.config.ts:1

```

What has gone wrong?

**Comment by thdxr** [comment]
can you try with `--print-logs`

**Comment by eivindgi** [comment]
Thank you for looking at this.
Here's the output with print-logs on

```
❯ npx sst@latest init --print-logs
time=2024-10-10T10:59:05.226+02:00 level=INFO msg="checking for pulumi" path="/Users/eivind/Library/Application Support/sst/bin/pulumi"
time=2024-10-10T10:59:05.550+02:00 level=INFO msg="checking for bun" path="/Users/eivind/Library/Application Support/sst/bin/bun"
time=2024-10-10T10:59:05.568+02:00 level=INFO msg="bun install"
time=2024-10-10T10:59:05.568+02:00 level=INFO msg="bun downloading" url=https://github.com/oven-sh/bun/releases//download/bun-v1.1.29/bun-darwin-x64-baseline.zip

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║   
   ╚════██║╚════██║   ██║   
   ███████║███████║   ██║   
   ╚══════╝╚══════╝   ╚═╝   

>  Remix detected. This will...
   - create an sst.config.ts
   - add sst to package.json

  Template: remix

time=2024-10-10T10:59:13.550+02:00 level=INFO msg="creating project" name=aws-remix
time=2024-10-10T10:59:13.554+02:00 level=INFO msg=step type=copy
time=2024-10-10T10:59:13.555+02:00 level=INFO msg="copying template" path=templates/remix/files/sst.config.ts
time=2024-10-10T10:59:13.556+02:00 level=INFO msg=step type=npm
time=2024-10-10T10:59:13.557+02:00 level=INFO msg="installing npm package" package=sst version=""
time=2024-10-10T10:59:13.557+02:00 level=INFO msg="reading package.json" file=package.json
time=2024-10-10T10:59:13.561+02:00 level=INFO msg="fetching latest version" package=sst
time=2024-10-10T10:59:13.561+02:00 level=INFO msg="getting package" name=sst version=latest
time=2024-10-10T10:59:14.203+02:00 level=INFO msg="latest version" version=3.1.74
⠋  Installing providers...time=2024-10-10T10:59:14.216+02:00 level=INFO msg="esbuild building" out=/Users/eivind/projects/aws-remix/.sst/platform/sst.config.1728550754216.mjs
⠙  Installing providers...time=2024-10-10T10:59:14.317+02:00 level=INFO msg="esbuild built" outfile=/Users/eivind/projects/aws-remix/.sst/platform/sst.config.1728550754216.mjs
time=2024-10-10T10:59:14.320+02:00 level=INFO msg="evaluating config"
time=2024-10-10T10:59:14.374+02:00 level=INFO msg="config evaluated"
time=2024-10-10T10:59:14.376+02:00 level=INFO msg="installing platform"
⠹  Installing providers...time=2024-10-10T10:59:14.441+02:00 level=INFO msg="installing deps"
time=2024-10-10T10:59:14.442+02:00 level=INFO msg="getting package" name=@sst-provider/aws version=latest
⠼  Installing providers...time=2024-10-10T10:59:14.654+02:00 level=INFO msg="getting package" name=@pulumi/aws version=latest
⠧  Installing providers...time=2024-10-10T10:59:14.993+02:00 level=INFO msg="writing package.json"
time=2024-10-10T10:59:14.994+02:00 level=INFO msg="adding dependency" name=aws
time=2024-10-10T10:59:14.997+02:00 level=INFO msg="fetching deps"
⠧  Installing providers...time=2024-10-10T10:59:20.054+02:00 level=ERROR msg="exited with error" err="failed to run bun install "
✕  Unexpected error occurred. Please check the logs in .sst/log/sst.log
```

**Comment by advancegabrielguihurt** [comment]
Having the same issue, but with bun instead.

I also don't have a log file and my `sst.config.ts` is exactly like @eivindgi.

_Certain path names were redacted for privacy._

```
$ bunx --bun sst@latest init --print-logs
[0.03ms] ".env"
time=2024-10-11T00:16:06.868-04:00 level=INFO msg="checking for pulumi" path=/home/<USER>/.config/sst/bin/pulumi
time=2024-10-11T00:16:07.212-04:00 level=INFO msg="checking for bun" path=/home/<USER>/.config/sst/bin/bun

   ███████╗███████╗████████╗
   ██╔════╝██╔════╝╚══██╔══╝
   ███████╗███████╗   ██║   
   ╚════██║╚════██║   ██║   
   ███████║███████║   ██║   
   ╚══════╝╚══════╝   ╚═╝   

>  Remix detected. This will...
   - create an sst.config.ts
   - add sst to package.json

✓  Template: remix

time=2024-10-11T00:16:10.219-04:00 level=INFO msg="creating project" name=<PROJECT_NAME>
time=2024-10-11T00:16:10.219-04:00 level=INFO msg=step type=copy
time=2024-10-11T00:16:10.219-04:00 level=INFO msg="copying template" path=templates/remix/files/sst.config.ts
time=2024-10-11T00:16:10.219-04:00 level=INFO msg=step type=npm
time=2024-10-11T00:16:10.219-04:00 level=INFO msg="installing npm package" package=sst version=""
time=2024-10-11T00:16:10.219-04:00 level=INFO msg="reading package.json" file=package.json
time=2024-10-11T00:16:10.220-04:00 level=INFO msg="fetching latest version" package=sst
time=2024-10-11T00:16:10.220-04:00 level=INFO msg="getting package" name=sst version=latest
time=2024-10-11T00:16:10.870-04:00 level=INFO msg="latest version" version=3.1.78
⠋  Installing providers...time=2024-10-11T00:16:10.871-04:00 level=INFO msg="esbuild building" out=/home/<USER>/Projects/<PROJECT_NAME>/.sst/platform/sst.config.1728620170871.mjs
time=2024-10-11T00:16:10.874-04:00 level=INFO msg="esbuild built" outfile=/home/<USER>/Projects/<PROJECT_NAME>/.sst/platform/sst.config.1728620170871.mjs
time=2024-10-11T00:16:10.874-04:00 level=INFO msg="evaluating config"
time=2024-10-11T00:16:10.880-04:00 level=INFO msg="config evaluated"
time=2024-10-11T00:16:10.880-04:00 level=INFO msg="installing platform"
time=2024-10-11T00:16:10.956-04:00 level=INFO msg="installing deps"
⠧  Installing providers...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x167ce16]

goroutine 1 [running]:
github.com/sst/ion/pkg/project.(*Project).generateProviderLock(0xc000b62100)
        /home/runner/work/ion/ion/pkg/project/install.go:197 +0x76
github.com/sst/ion/pkg/project.(*Project).Install(0xc000b62100)
        /home/runner/work/ion/ion/pkg/project/install.go:41 +0x58
main.CmdInit(0xc000b62700)
        /home/runner/work/ion/ion/cmd/sst/init.go:211 +0x153b
github.com/sst/ion/cmd/sst/cli.(*Cli).Run(0xc000b62700)
        /home/runner/work/ion/ion/cmd/sst/cli/cli.go:90 +0x124
main.run()
        /home/runner/work/ion/ion/cmd/sst/main.go:125 +0x225
main.main()
        /home/runner/work/ion/ion/cmd/sst/main.go:57 +0x4cb
error: "sst" exited with code 1 (SIGHUP)
```

Error as context for why I'm using the the `--bun` flag in the package runner.
```
$ bunx sst@latest --print-logs
/tmp/sst@latest--bunx/node_modules/sst/bin/sst.mjs:2
import { createRequire } from 'node:module';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error: "sst" exited with code 1 (SIGHUP)
```

```
$ bun --version
1.0.2
$ uname -a
Linux <DESKTOP_NAME> 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by eivindgi** [comment]
@thdxr have you had a chance to look at this?
