### ISSUE TITLE
[Bug] ".sst/artifacts/{PROJECT}/prerendered: copy_file_range: is a directory

### ISSUE THREAD

**Issue by joanMelchor** [sst/ion#1255]
We are using sst in our project and after upgrading from version 3.1.78 our deployments started breaking. We haven't made any changes other than bumping the version, tried versions 3.2.0 to 3.2.6 but no luck, always the same error.

It's a sveltekit project. Full error:
```
Error: write /home/xxxx/xxxx/xxxx/.sst/artifacts/xxxx/prerendered: copy_file_range: is a directory
       at IncomingMessage.<anonymous> (file:///xxxx/xxxx/xxxx/xxx/.sst/platform/src/components/rpc/rpc.ts:42:22)
       at IncomingMessage.emit (node:events:529:35)
       at IncomingMessage.emit (node:domain:489:12)
       at endReadableNT (node:internal/streams/readable:1368:12)
       at processTicksAndRejections (node:internal/process/task_queues:82:21) {
     promise: Promise { <rejected> [Circular *1] }
   }
```

For now I'm fixing the version of the libray, again I haven't made any code changes other than updating the library version. Thanks for your help!

**Comment by rayli09** [comment]
hitting same error cc @thdxr
reproable on 3.2.11

```ts

const migrator = new sst.aws.Function("SqliteMigrator", {
  handler: "./packages/core/src/migrator.handler",
  link: [...allSecrets],
  memory: "256 MB",
  copyFiles: [
    {
      from: "./packages/core/migrations",
      to: "./migrations",
    },
  ],
});
```

**Comment by rracariu** [comment]
Got similar error:
```bash
Failed    
Error: read /Users/foo/bar/.svelte-kit/svelte-kit-sst/prerendered: is a directory
at IncomingMessage.<anonymous> (file:///Users/foo/sst/.sst/platform/src/components/rpc/rpc.ts:42:22)
       at IncomingMessage.emit (node:events:531:35)
       at IncomingMessage.emit (node:domain:488:12)
       at endReadableNT (node:internal/streams/readable:1698:12)
       at processTicksAndRejections (node:internal/process/task_queues:90:21) {
     promise: Promise { <rejected> [Circular *1] }
   }
```

**Comment by bigbyte-dom** [comment]
Seeing the same issue on 3.2.12. Rolling back to 3.1.78 does the trick. 

```
 Error: write /workspace/app/.sst/artifacts/XXXXXX-src/migrations: copy_file_range: is a directory
       at IncomingMessage.<anonymous> (file:///workspace/app/.sst/platform/src/components/rpc/rpc.ts:42:22)
       at IncomingMessage.emit (node:events:532:35)
       at IncomingMessage.emit (node:domain:488:12)
       at endReadableNT (node:internal/streams/readable:1696:12)
       at processTicksAndRejections (node:internal/process/task_queues:82:21) {
     promise: Promise { <rejected> [Circular *1] }
   }
   ```

**Comment by rayli09** [comment]
> Seeing the same issue on 3.2.12. Rolling back to 3.1.78 does the trick.
> 
> ```
>  Error: write /workspace/app/.sst/artifacts/XXXXXX-src/migrations: copy_file_range: is a directory
>        at IncomingMessage.<anonymous> (file:///workspace/app/.sst/platform/src/components/rpc/rpc.ts:42:22)
>        at IncomingMessage.emit (node:events:532:35)
>        at IncomingMessage.emit (node:domain:488:12)
>        at endReadableNT (node:internal/streams/readable:1696:12)
>        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
>      promise: Promise { <rejected> [Circular *1] }
>    }
> ```

dumb question: what steps did u follow to roll back?

for me i did
1. change `package.json` and reinstall
2. run sst install
3. run sst deploy --stage <STG>
but i'm still seeing the err

**Comment by Chung-Peter** [comment]
I also ran into this issue and had to rollback to version 3.1.78 to get a successful deployment.
