### ISSUE TITLE
Deploying SST site on Docker via Assumed Role is resulting in deployment failure

### ISSUE THREAD

**Issue by itsfaraaz** [sst/ion#1267]
I am attempting to deploy via SST on a Docker Linux container. I have installed AWS CLI on the container. When I run the command `aws sts get-caller-identity` I get:

`{ "UserId": "AIDAVG7TGW6NUZQL4XI5L", "Account": "358602946459", "Arn": "arn:aws:iam::358602946459:user/docker" }`

This tells me that the Docker container is able to successfully access AWS account ID 358602946459.

What I am attempting to do here is make an SST.dev deployment. I have installed the SST CLI as well. I believe SST v3 under the hood uses Pulumi. My sst config file is this:

```
// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app() {
    return {
      name: "faraazxyz-dks94",
      removal: "remove",
      home: "aws",
      providers: {
        aws: {
          region: "us-east-1",
          allowedAccountIds: ["203918846642"],
          assumeRole: {
            roleArn: "arn:aws:iam::203918846642:role/<redacted>",
          },
          accessKey: process.env.AWS_ACCESS_KEY_ID,
          secretKey: process.env.AWS_SECRET_ACCESS_KEY,
        }
      }
    };
  },
  async run() {
    new sst.aws.Nextjs("faraazxyz-dks94", {
      
    domain: {
      name: "faraaz.xyz",
      redirects: ["www.faraaz.xyz"],
    
      aliases: ["faraazxyz-dks94.visioner.cloud","www.faraazxyz-dks94.visioner.cloud"]
    }
    });
  },
});
```

The `accessKey` and `secretKey` are for account ID 358602946459.

What I want to do is that I have given this Docker container access to the account ID 358602946459 (evident by the AWS CLI command above). What I want to do is deploy the site's resource to a different AWS account, with ID 203918846642. I have created a role that the main AWS account can assume to do this. I have verified that 358602946459 is able to assume the role in 203918846642 via the CLI:

```
# aws sts assume-role --role-arn arn:aws:iam::203918846642:role/<redacted> --role-session-name TestSession
{
    "Credentials": {
        "AccessKeyId": "<redcated>",
        "SecretAccessKey": "<redacted>",
        "SessionToken": "<redcated>",
        "Expiration": "2024-10-13T05:17:42+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "<redcated>:TestSession",
        "Arn": "arn:aws:sts::203918846642:assumed-role/<redacted>/TestSession"
    }
}
```

When I run `sst deploy --stage production` on the Docker container, i then get this error:

```
|  Updated     faraazxyz-dks94 sst:aws:Nextjs → faraazxyz-dks94Build sst:Run (51.6s)
panic: interface conversion: interface {} is string, not resource.PropertyMap
goroutine 42 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/properties.go:462
github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0xc0092b4600, {0x19b6acde?, 0x0?})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:624 +0x13ca
github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func26(0xc0092b4600, {0x1bcf1ec0, 0xc003321548})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:790 +0xff
github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(provider).runPreConfigureCallback(0xc007c59188, {0x1bfaeb38?, 0xc00917ef60?}, 0xc0092b4600)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:131 +0x104
github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(provider).CheckConfigWithContext(0xc007c59188, {0x1bfaeb38?, 0xc00913f920?}, {0xc00844af00, 0x57}, 0x2c710e0?, 0xc00917ea20, 0x50?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:84 +0x68e
github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(provider[...]).CheckConfigWithContext(0xc00433a8f0, {0x1bfaeb38?, 0xc00913f920}, {0xc00844af00, 0x57}, 0xc00913fb00, 0xc00913fb30, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/configencoding/provider.go:74 +0xf5
github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(providerServer).CheckConfig(0xc00913e090, {0x1bfaeb38, 0xc00913f920}, 0xc00914a200)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/plugin/provider_server.go:227 +0x203
github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).CheckConfig.func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:127 +0x6f
github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42
created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 40
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79
|  Error       AwsProvider sst:us-east-1
|  rpc error: code = Unavailable desc = error reading from server: EOF
✕  Failed    
   AwsProvider sst:us-east-1
   rpc error: code = Unavailable desc = error reading from server: EOF
```

I am unsure where this could be coming from as the error message is ambiguous. Any help is appreciated here.

**Comment by itsfaraaz** [comment]
Another update, I removed accessKey and secretKey and am getting a similar error still:

```
2024-10-12 21:41:33 panic: interface conversion: interface {} is string, not resource.PropertyMap
2024-10-12 21:41:33 goroutine 14 [running]:
2024-10-12 21:41:33 github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/properties.go:462
2024-10-12 21:41:33 github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0xc003b90510, {0x19b6acde?, 0x0?})
2024-10-12 21:41:33     /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:624 +0x13ca
2024-10-12 21:41:33 github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func26(0xc003b90510, {0x1bcf1ec0, 0xc009364208})
2024-10-12 21:41:33     /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:790 +0xff
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).runPreConfigureCallback(0xc008895888, {0x1bfaeb38?, 0xc003b7adb0?}, 0xc003b90510)
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:131 +0x104
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).CheckConfigWithContext(0xc008895888, {0x1bfaeb38?, 0xc003b3d530?}, {0xc008caa000, 0x57}, 0x2c710e0?, 0xc003b7a8a0, 0xc0?)
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:84 +0x68e
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).CheckConfigWithContext(0xc006c21c70, {0x1bfaeb38?, 0xc003b3d530}, {0xc008caa000, 0x57}, 0xc003b3d710, 0xc003b3d740, 0x1)
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/configencoding/provider.go:74 +0xf5
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).CheckConfig(0xc003a8e330, {0x1bfaeb38, 0xc003b3d530}, 0xc008ab5380)
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/plugin/provider_server.go:227 +0x203
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).CheckConfig.func1()
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:127 +0x6f
2024-10-12 21:41:33 github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42
2024-10-12 21:41:33 created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 12
2024-10-12 21:41:33     /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79
2024-10-12 21:41:33 |  Error       AwsProvider sst:us-east-1
2024-10-12 21:41:33 |  rpc error: code = Unavailable desc = error reading from server: EOF
2024-10-12 21:41:33 time=2024-10-13T04:41:33.994Z level=ERROR msg="stack run failed" error="failed to run update: exit status 255\ncode: 255\nstdout: Updating (production):\n@ updating....\nDownloading plugin random-4.16.6: starting\nDownloading plugin vercel-1.11.0: starting\nDownloading plugin tls-5.0.1: starting\nDownloading plugin aws-6.55.0: starting\nDownloading plugin docker-build-0.0.6: starting\nDownloading plugin cloudflare-5.37.1: starting\nDownloading plugin random-4.15.0: starting\n@ updating....\nDownloading plugin vercel-1.11.0: done\nInstalling plugin vercel-1.11.0: starting\nInstalling plugin vercel-1.11.0: done\nDownloading plugin tls-5.0.1: done\nInstalling plugin tls-5.0.1: starting\nDownloading plugin random-4.15.0: done\n@ updating....\nInstalling plugin random-4.15.0: starting\nInstalling plugin tls-5.0.1: done\nInstalling plugin random-4.15.0: done\nDownloading plugin random-4.16.6: done\nInstalling plugin random-4.16.6: starting\n@ updating....\nDownloading plugin cloudflare-5.37.1: done\nInstalling plugin cloudflare-5.37.1: starting\nDownloading plugin docker-build-0.0.6: done\nInstalling plugin docker-build-0.0.6: starting\nInstalling plugin random-4.16.6: done\n@ updating....\nInstalling plugin cloudflare-5.37.1: done\nInstalling plugin docker-build-0.0.6: done\n@ updating.....\nDownloading plugin aws-6.55.0: done\nInstalling plugin aws-6.55.0: starting\n@ updating...........\nInstalling plugin aws-6.55.0: done\n\n@ updating.....\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \n@ updating.........\n ~  pulumi-nodejs:dynamic:Resource faraazxyz-dks94Build.sst.Run updating (0s) [diff: ~env,version]\n@ updating....................................................................\n ~  pulumi-nodejs:dynamic:Resource faraazxyz-dks94Build.sst.Run updated (64s) [diff: ~env,version]\n@ updating....\n    aws:iam:Role faraazxyz-dks94RevalidationSeederRole  warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94RevalidationSeederRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n    aws:iam:Role faraazxyz-dks94RevalidationSeederRole  warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94RevalidationSeederRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n    aws:iam:Role faraazxyz-dks94DefaultRole  warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94DefaultRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n    aws:iam:Role faraazxyz-dks94DefaultRole  warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94DefaultRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n@ updating.....\n    pulumi:providers:aws AwsProvider.sst.us-east-1  warning: Type checking failed:\n    pulumi:pulumi:Stack faraazxyz-dks94-production running panic: interface conversion: interface {} is string, not resource.PropertyMap\n    pulumi:pulumi:Stack faraazxyz-dks94-production running goroutine 14 [running]:\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/properties.go:462\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0xc003b90510, {0x19b6acde?, 0x0?})\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:624 +0x13ca\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func26(0xc003b90510, {0x1bcf1ec0, 0xc009364208})\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:790 +0xff\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).runPreConfigureCallback(0xc008895888, {0x1bfaeb38?, 0xc003b7adb0?}, 0xc003b90510)\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:131 +0x104\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).CheckConfigWithContext(0xc008895888, {0x1bfaeb38?, 0xc003b3d530?}, {0xc008caa000, 0x57}, 0x2c710e0?, 0xc003b7a8a0, 0xc0?)\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:84 +0x68e\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).CheckConfigWithContext(0xc006c21c70, {0x1bfaeb38?, 0xc003b3d530}, {0xc008caa000, 0x57}, 0xc003b3d710, 0xc003b3d740, 0x1)\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/configencoding/provider.go:74 +0xf5\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).CheckConfig(0xc003a8e330, {0x1bfaeb38, 0xc003b3d530}, 0xc008ab5380)\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/plugin/provider_server.go:227 +0x203\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).CheckConfig.func1()\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:127 +0x6f\n    pulumi:pulumi:Stack faraazxyz-dks94-production running github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42\n    pulumi:pulumi:Stack faraazxyz-dks94-production running created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 12\n    pulumi:pulumi:Stack faraazxyz-dks94-production running \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79\n    pulumi:providers:aws AwsProvider.sst.us-east-1  error: rpc error: code = Unavailable desc = error reading from server: EOF\n    pulumi:providers:aws AwsProvider.sst.us-east-1 **failed** 1 error; 1 warning\n    pulumi:pulumi:Stack faraazxyz-dks94-production  22 messages\nDiagnostics:\n  pulumi:pulumi:Stack (faraazxyz-dks94-production):\n    panic: interface conversion: interface {} is string, not resource.PropertyMap\n    goroutine 14 [running]:\n    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/properties.go:462\n    github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0xc003b90510, {0x19b6acde?, 0x0?})\n    \t/home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:624 +0x13ca\n    github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func26(0xc003b90510, {0x1bcf1ec0, 0xc009364208})\n    \t/home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:790 +0xff\n    github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).runPreConfigureCallback(0xc008895888, {0x1bfaeb38?, 0xc003b7adb0?}, 0xc003b90510)\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:131 +0x104\n    github.com/pulumi/pulumi-terraform-bridge/pf/tfbridge.(*provider).CheckConfigWithContext(0xc008895888, {0x1bfaeb38?, 0xc003b3d530?}, {0xc008caa000, 0x57}, 0x2c710e0?, 0xc003b7a8a0, 0xc0?)\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfbridge/provider_checkconfig.go:84 +0x68e\n    github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).CheckConfigWithContext(0xc006c21c70, {0x1bfaeb38?, 0xc003b3d530}, {0xc008caa000, 0x57}, 0xc003b3d710, 0xc003b3d740, 0x1)\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/configencoding/provider.go:74 +0xf5\n    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).CheckConfig(0xc003a8e330, {0x1bfaeb38, 0xc003b3d530}, 0xc008ab5380)\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/internal/plugin/provider_server.go:227 +0x203\n    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).CheckConfig.func1()\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:127 +0x6f\n    github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42\n    created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 12\n    \t/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79\n\n  aws:iam:Role (faraazxyz-dks94RevalidationSeederRole):\n    warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94RevalidationSeederRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n\n  aws:iam:Role (faraazxyz-dks94DefaultRole):\n    warning: urn:pulumi:production::faraazxyz-dks94::sst:aws:Nextjs$sst:aws:Function$aws:iam/role:Role::faraazxyz-dks94DefaultRole verification warning: The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of this argument), use the aws_iam_role_policies_exclusive resource as well.\n\n  pulumi:providers:aws (AwsProvider.sst.us-east-1):\n    warning: Type checking failed:\n    \n                 Unexpected type at field \"assumeRole\":\n                     expected object type, got \"{\\\"roleArn\\\":\\\"arn:aws:iam... of type string\n    \n             Type checking is still experimental. If you believe that a warning is incorrect,\n             please let us know by creating an issue at https://github.com/pulumi/pulumi-terraform-bridge/issues.\n             This will become a hard error in the future.\n    error: rpc error: code = Unavailable desc = error reading from server: EOF\n\nResources:\n    ~ 1 updated\n    25 unchanged\n\nDuration: 1m17s\n\n\nstderr: \n"
```
