### ISSUE TITLE
`[ERR_REQUIRE_ESM]: require() of ES Module`

### ISSUE THREAD

**Issue by thdxr** [sst/ion#142]
```
   Error [ERR_REQUIRE_ESM]: require() of ES Module /home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/string-width/index.js from /home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/wide-align/align.js not supported.
   Instead change the require of index.js in /home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/wide-align/align.js:2:19)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/gauge/lib/render-template.js:2:13)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/gauge/lib/plumbing.js:3:22)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/gauge/lib/index.js:2:16)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/npmlog/lib/log.js:3:13)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@npmcli/arborist/lib/tracker.js:1:16)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@npmcli/arborist/lib/arborist/index.js:40:3)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@npmcli/arborist/lib/index.js:1:18)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:38:31)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@pulumi/pulumi/runtime/index.js:22:19)
       at Object.<anonymous> (/home/luke/Workspace/repos/strabo-v2/.sst/platform/node_modules/@pulumi/pulumi/index.js:48:30) {
     code: 'ERR_REQUIRE_ESM'
   }
```

some people have reported this error - it's related to bun (use by sst internally) not installing dependencies correctly

as a work around you can pass NO_BUN=true as an environment variable but we need help recreating it and isolating the cause

**Comment by coronapl** [comment]
@thdxr I am not completely sure if this related, but apparently we only face this problem when using Linux x64. On MacOs seems to work fine. I will keep informed if we find any more clues.

**Comment by thdxr** [comment]
interesting - i'm using linux x64 and haven't run into it - does setting `NO_BUN=true` fix it?

**Comment by coronapl** [comment]
Yes, `NO_BUN=true` fixes the problem.

**Comment by brogine** [comment]
Happening also on MacOS Sonoma Intel.

```
×  Failed
time=2024-04-01T06:41:43.863-03:00 level=INFO msg="INFO pushing state app=test stage=dev from=/Users/x/Documents/Projects/test/.sst/.pulumi/stacks/test/dev.json"
   Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/x/Documents/Projects/test/.sst/platform/node_modules/string-width/index.js from /Users/x/Documents/Projects/test/.sst/platform/node_modules/wide-align/align.js not supported.
   Instead change the require of index.js in /Users/x/Documents/Projects/test/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/wide-align/align.js:2:19)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/gauge/lib/render-template.js:2:13)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/gauge/lib/plumbing.js:3:22)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/gauge/lib/index.js:2:16)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/npmlog/lib/log.js:3:13)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@npmcli/arborist/lib/tracker.js:1:16)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@npmcli/arborist/lib/arborist/index.js:40:3)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@npmcli/arborist/lib/index.js:1:18)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:38:31)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@pulumi/pulumi/runtime/index.js:22:19)
       at Object.<anonymous> (/Users/x/Documents/Projects/test/.sst/platform/node_modules/@pulumi/pulumi/index.js:48:30) {
     code: 'ERR_REQUIRE_ESM'
   }
```

**Comment by xonha** [comment]
Same error when trying to deploy using github actions

![image](https://github.com/sst/ion/assets/25267506/7aadb513-ba4c-4ab9-ad28-fd9f6b242d3f)

**Comment by yassine-safraoui** [comment]
Same here on Intel x86 Ubuntu:
`|  Error        Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/string-width/index.js from /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js not supported.
|  Instead change the require of index.js in /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
|  at Object.<anonymous> (/home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js:2:19) {
|  code: 'ERR_REQUIRE_ESM'
|  }

×  Failed
   Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/string-width/index.js from /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js not supported.
   Instead change the require of index.js in /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js:2:19) {
     code: 'ERR_REQUIRE_ESM'
`

**Comment by yassine-safraoui** [comment]
Facing the same issue here when adding sst to an already existing NextJS app on Intel x86 Ubuntu:
```
|  Error        Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/string-width/index.js from /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js not supported.
|  Instead change the require of index.js in /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
|  at Object.<anonymous> (/home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js:2:19) {
|  code: 'ERR_REQUIRE_ESM'
|  }

×  Failed
   Error [ERR_REQUIRE_ESM]: require() of ES Module /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/string-width/index.js from /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js not supported.
   Instead change the require of index.js in /home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/home/yassine/Documents/side-programming-projects/project/.sst/platform/node_modules/wide-align/align.js:2:19) {
     code: 'ERR_REQUIRE_ESM'
```

**Comment by thdxr** [comment]
are these monorepos by chance?

**Comment by yassine-safraoui** [comment]
> are these monorepos by chance?

No, I actually got around this by deleting the .sst/platform folder, but I suppose that's not a fix

**Comment by VirtuaBoza** [comment]
Just ran into this for the first time in a GH workflow running on `ubuntu-latest`. Not sure if that helps as a clue. I altered my script to set `NO_BUN=true` as noted above, and that worked.

**Comment by sicknarlo** [comment]
I just ran into this issue. Brand new install of SST on venture 13. Following the NextJ start guide.

**Comment by jayair** [comment]
@sicknarlo Can you try the `NO_BUN=true` like above?

**Comment by sicknarlo** [comment]
@jayair I was able to get it working by deleting the `.sst` directory and rerunning sst init, but I figured I'd try to at least drop what little I had here to help. I didn't do anything that felt edge casey or out of the ordinary.

**Comment by WatchTheGuide** [comment]
Got the same error on macOS Sonoma 14.4.1 (Intel) with a fresh installation of the Next.js. First  installed Next.js, then SST CLI, then ran `sst init`. Then I removed everything, installed Next.js and ran `set init`. The second had no that issue, and app is running. Maybe the issue was caused by incorrect installation order.

**Comment by yassine-safraoui** [comment]
I think the fact that it worked for @sicknarlo after deleting .sst folder means that there is an issue with sst init, somehow the .sst it creates doesn't work but when we run some other command it works, maybe NO_BUN has to be set to true before running sst init, because when I deleted the .sst I already tried sst dev while setting NO_BUN to true so maybe that's why it worked for me

**Comment by kldeb** [comment]
in package.json i did this and it didn't work:
`"dev": "NO_BUN=true sst dev remix vite:dev",`

is that right? 

In my case, I'm running a project i created on another machine (both macs), so git clone, npm install then npm run dev.

**Comment by yashwanth2804** [comment]
> @jayair I was able to get it working by deleting the `.sst` directory and rerunning sst init, but I figured I'd try to at least drop what little I had here to help. I didn't do anything that felt edge casey or out of the ordinary.

Yes this approach worked bby deleting .sst and running sst init again

**Comment by sam-goodwin** [comment]
Getting this on Mac M3

**Comment by sam-goodwin** [comment]
`rm -rf .sst` also fixed it for me. 

In my case, `sst init`, crashed because of some weird EC2 error. I wasn't logging into SST and providing an AWS profile. Providing the profile fixed it, but maybe left me in a dirty state?

**Comment by thdxr** [comment]
i attempted a fix for this in 0.0.292 - going to close this for now and comment if you still run into it

**Comment by Jarred-Sumner** [comment]
We are looking into a fix for this on Bun's end

**Comment by stuartbourhill** [comment]
commenting because I just bumped into this while running `sst deploy` inside a Github Action (ubuntu-latest) on sst version 0.0.295. `NO_BUN=true` worked 👍

**Comment by leeTheGit** [comment]
Yes unfortunately this is still an issue as the previous attempt at a fix moved the error to the next script in the chain with the same [ERR_REQUIRE_ESM] issue.  I assume pinning package versions would be a case of whack-a-mole until fixed at Bun's end.  

Until then, it seems we'll need the NO_BUN=true, or deletion of the .sst folder and re-install

**Comment by Jarred-Sumner** [comment]
@leeTheGit @stuartbourhill this should be fixed in Bun v1.1.4, which released a few hours ago. Please let us know if you continue to run into this issue

**Comment by this-fifo** [comment]
I was excited to try out `ion` but ran into this issue right out the gate too. All I did was follow the docs in https://ion.sst.dev/docs/start/aws/nextjs/

I ran
```
npx create-next-app@latest
cd start-nextjs
```

Then
```
sst init
```

Which caused
```
❯ npm run dev

> start-nextjs@0.1.0 dev
> sst dev next dev

SST ❍ ion 0.0.296  ready!

➜  App:        start-nextjs
   Stage:      fifo
   Console:    https://console.sst.dev/local/start-nextjs/fifo

|  Error        Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/strip-ansi/index.js from /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js not supported.
|  Instead change the require of /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/strip-ansi/index.js in /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
|  at Object.<anonymous> (/Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js:2:19) {
|  code: 'ERR_REQUIRE_ESM'
|  }

×  Failed
   Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/strip-ansi/index.js from /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js not supported.
   Instead change the require of /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/strip-ansi/index.js in /Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
       at Object.<anonymous> (/Users/fifo/Sandbox/start-nextjs/.sst/platform/node_modules/string-width/index.js:2:19) {
     code: 'ERR_REQUIRE_ESM'
   }
```

**Comment by this-fifo** [comment]
this morning I tried setting it up again and did `rm -rf .sst sst-env.d.ts sst.config.ts` and then `sst init` and it now works.

**Comment by TheHolyWaffle** [comment]
Ran into this while following the Amazon API Gateway getting started: https://ion.sst.dev/docs/start/aws/api/

Solution was to `rm -rf .sst` followed by an `sst install`

**Comment by kane50613** [comment]
It works on my machine but broken on gh action

```
|  Error        Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/easy-event/easy-event/.sst/platform/node_modules/strip-ansi/index.js from /home/runner/work/easy-event/easy-event/.sst/platform/node_modules/string-width/index.js not supported.
|  Instead change the require of /home/runner/work/easy-event/easy-event/.sst/platform/node_modules/strip-ansi/index.js in /home/runner/work/easy-event/easy-event/.sst/platform/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
|  at Object.<anonymous> (/home/runner/work/easy-event/easy-event/.sst/platform/node_modules/string-width/index.js:2:19) {
|  code: 'ERR_REQUIRE_ESM'
|  }
```

**Comment by RyanTheAllmighty** [comment]
Also ran into this when deploying through GitHub actions, adding `NO_BUN: true` to the env of my sst install (not sure if it's needed to have that env there) and deploy worked:

```
      - name: Install SST dependencies
        env:
          NO_BUN: true
        run: sst install

      - name: Deploy
        env:
          NO_BUN: true
        run: sst deploy
```

**Comment by MilanObrenovic** [comment]
> Ran into this while following the Amazon API Gateway getting started: https://ion.sst.dev/docs/start/aws/api/
> 
> Solution was to `rm -rf .sst` followed by an `sst install`

this fixed it for me
