### ISSUE TITLE
'Runtime.HandlerNotFound' when accessing deployed site

### ISSUE THREAD

**Issue by Jhinger** [sst/ion#444]
Currently trying to deploy a barebones SolidStart app in ion - the build itself is successful and I can preview the app by running `node ./output/server/index.mjs` or `sst dev npm run dev`, however when I try to access the app at the cloudfront url I get error code 502 and I see the following error in console.sst:

```yaml
Uncaught Exception	{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": ".output/server/index.handler is undefined or not exported",
  "stack": [
    "Runtime.HandlerNotFound: .output/server/index.handler is undefined or not exported",
    "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}
```

Here is my sst.config:

```
import * as aws from "@pulumi/aws";

export default $config({
  app(input) {
    return {
      name: "rmc",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    const db = new aws.rds.Instance("Database", {
      instanceClass: "db.t4g.micro",
      allocatedStorage: 20,
      dbName: "rmcdb",
      engine: "postgres",
      username: "",
      password: "",
      skipFinalSnapshot: true,
      identifierPrefix: "rmc",
    })
    new sst.aws.SolidStart("RMC", {
      link: [db]
    })

    return {
      app: $app.name,
      db: db.dbName,
      stage: $app.stage,
    }
  },
});
```

Any help on resolving this would be appreciated.

**Comment by Jhinger** [comment]
Yeah - everything is the same
```
  "dependencies": {
    "@aws-sdk/client-rds-data": "^3.577.0",
    "@pulumi/aws": "^6.36.0",
    "@solidjs/router": "^0.13.3",
    "@solidjs/start": "^1.0.0-rc.0",
    "autoprefixer": "^10.4.19",
    "drizzle-kit": "^0.21.2",
    "drizzle-orm": "^0.29.5",
    "postcss": "^8.4.38",
    "solid-js": "^1.8.17",
    "sst": "ion",
    "tailwindcss": "^3.4.3",
    "vinxi": "^0.3.11"
  },
  "engines": {
    "node": ">=18"
  },
  "devDependencies": {
    "@types/aws-lambda": "8.10.138"
  },
  "overrides": {
    "nitropack": "npm:nitropack-nightly@latest"
  }
```

**Comment by Jhinger** [comment]
I tried this again following the minimal SolidStart example, and I'm still seeing the same issue when deploying the app so it has to be something on my end - but I'm not exactly sure what.

**Comment by thdxr** [comment]
what package manager are you using? we have to force use of the nightly of nitropack and it's possible your package manager is not resolving it properly

**Comment by Jhinger** [comment]
I'm using npm - I also tried with Bun however and got the same result.

**Comment by Jhinger** [comment]
Ah, found my issue - I didn't have any value set for server.preset in app.config.ts 😐. Updating the value to aws-lambda resolved the issue.

```
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  server: {
    preset: "aws-lambda"
  },
  vite: {
    resolve: {
      alias: {
        "@": "/src"
      }
    },
  }
});

```
