### ISSUE TITLE
Authorization errors

### ISSUE THREAD

**Issue by felipemotarocha** [sst/ion#453]
Hey guys. I'm using SST on my app and it works fine, even though I'm getting A LOT of errors like these ones:

```
Routing failed. TypeError: Invalid URL
    at new URL (node:internal/url:796:36)
    at Ak (file:///var/task/index.mjs:2:7711)
    at um (file:///var/task/index.mjs:42:95211)
    at NS (file:///var/task/index.mjs:42:99446)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async zk (file:///var/task/index.mjs:42:100395)
    at async file:///var/task/index.mjs:2:13689 {
  code: 'ERR_INVALID_URL',
  input: 'https://o:orgid.ingest.:region.sentry.io/api/:projectid/envelope/%3Fhsts=0'
}
```

```
{
  clientName: 'S3Client',
  commandName: 'GetObjectCommand',
  input: {
    Bucket: 'doutor-sim-prod-doutorsimassets-ovxmssav',
    Key: '_cache/__fetch/-4xOGT0XP2DMNojABcP08/7020bbbcbbd3c080d9bf4c5cbf96d34353615adfedc321006f3f6188aea5f349'
  },
  error: AccessDenied: Access Denied
      at UM (file:///var/task/index.mjs:12:4767)
      at file:///var/task/index.mjs:12:4908
      at j (file:///var/task/index.mjs:39:74689)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///var/task/index.mjs:3:8997
      at async file:///var/task/index.mjs:39:6913
      at async file:///var/task/index.mjs:12:11163
      at async file:///var/task/index.mjs:42:46878
      at async file:///var/task/index.mjs:38:41890
      at async file:///var/task/index.mjs:38:42234 {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 403,
      requestId: 'AATQ2T0BD7GK4XYB',
      extendedRequestId: 'cxngD92p8lrDjyPzCzIkA4bzOs+3ShFdSFK7TwGPsONCySSDjmS5+Qzs2mKjNZSMOG16/mO4BYU=',
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    Code: 'AccessDenied',
    RequestId: 'AATQ2T0BD7GK4XYB',
    HostId: 'cxngD92p8lrDjyPzCzIkA4bzOs+3ShFdSFK7TwGPsONCySSDjmS5+Qzs2mKjNZSMOG16/mO4BYU='
  },
  metadata: {
    httpStatusCode: 403,
    requestId: 'AATQ2T0BD7GK4XYB',
    extendedRequestId: 'cxngD92p8lrDjyPzCzIkA4bzOs+3ShFdSFK7TwGPsONCySSDjmS5+Qzs2mKjNZSMOG16/mO4BYU=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

```

```
Failed to get fetch cache AccessDenied: Access Denied
    at UM (file:///var/task/index.mjs:12:4767)
    at file:///var/task/index.mjs:12:4908
    at j (file:///var/task/index.mjs:39:74689)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/task/index.mjs:3:8997
    at async file:///var/task/index.mjs:39:6913
    at async file:///var/task/index.mjs:12:11163
    at async file:///var/task/index.mjs:42:46878
    at async file:///var/task/index.mjs:38:41890
    at async file:///var/task/index.mjs:38:42234 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'AATQ2T0BD7GK4XYB',
    extendedRequestId: 'cxngD92p8lrDjyPzCzIkA4bzOs+3ShFdSFK7TwGPsONCySSDjmS5+Qzs2mKjNZSMOG16/mO4BYU=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'AccessDenied',
  RequestId: 'AATQ2T0BD7GK4XYB',
  HostId: 'cxngD92p8lrDjyPzCzIkA4bzOs+3ShFdSFK7TwGPsONCySSDjmS5+Qzs2mKjNZSMOG16/mO4BYU='
}
```

```
Routing failed. TypeError: Invalid URL
    at new URL (node:internal/url:796:36)
    at Ak (file:///var/task/index.mjs:2:7711)
    at um (file:///var/task/index.mjs:42:95211)
    at NS (file:///var/task/index.mjs:42:99446)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async zk (file:///var/task/index.mjs:42:100395)
    at async file:///var/task/index.mjs:2:13689 {
  code: 'ERR_INVALID_URL',
  input: 'https://o:orgid.ingest.:region.sentry.io/api/:projectid/envelope/%3Fhsts=0'
}
```

Like I said, the app seems to be working fine but these errors are strange and it's very annoying to have a lot of them spammed on my error tracking tools.

Can someone help me with this?

**Comment by felipemotarocha** [comment]
I'm getting thousands of this error per hour and this is exploding my costs with S3. Here's the bucket `doutor-sim-prod-doutorsimassets-ovxmssav` policy:

{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Deny",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::doutor-sim-preview-doutorsimassets-rtverhht/*",
				"arn:aws:s3:::doutor-sim-preview-doutorsimassets-rtverhht"
			],
			"Condition": {
				"Bool": {
					"aws:SecureTransport": "false"
				}
			}
		},
		{
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E11VGZIMUVRRSU"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::doutor-sim-preview-doutorsimassets-rtverhht/*"
		}
	]
}

**Comment by jayair** [comment]
Did this just start happening? It sounds like your local credentials don't have access to upload to that bucket?

**Comment by fwang** [comment]
i'm looking at the S3 error, it's trying to access _cache/__fetch/*

it seems the server function doesn't have permission to access the ISR cache in S3

Can you check the IAM permission on the server function and see if it has the necessary permissions?

**Comment by EdwardNavarro** [comment]
That's make sense, I'm getting the same error since I turned on ISR.

**Comment by jschuur** [comment]
> Can you check the IAM permission on the server function and see if it has the necessary permissions?

@fwang Where would those permissions be? In \*SiteDefaultRole\* ? This is from 'inline' there:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::coworking-party-preview-siteassets-reoekxhm/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "sqs:SendMessage",
                "sqs:GetQueueUrl",
                "sqs:GetQueueAttributes"
            ],
            "Resource": "arn:aws:sqs:us-east-1:030731221117:coworking-party-preview-SiteRevalidationQueueQueue.fifo"
        },
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:UpdateItem",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:PutItem",
                "dynamodb:GetShardIterator",
                "dynamodb:GetRecords",
                "dynamodb:GetItem",
                "dynamodb:DescribeTable",
                "dynamodb:DeleteItem",
                "dynamodb:ConditionCheckItem",
                "dynamodb:BatchWriteItem",
                "dynamodb:BatchGetItem"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:030731221117:table/coworking-party-preview-SiteRevalidationTable/*",
                "arn:aws:dynamodb:us-east-1:030731221117:table/coworking-party-preview-SiteRevalidationTable"
            ]
        }
    ]
}
```

**Comment by VersorVerbi** [comment]
I'm still seeing this as well (SST v3.0.53), and (not looking at SST's code at the moment) I think it might be a race condition. The SST console has this error occurring at `04:47:27.206` but S3 shows the Last-Modified as `04:47:28`. Without more specificity on the Last-Modified field, it might just be a rounding error, but it seems plausible that a request is still in the process of being cached when it's requested again.

In addition, my Lambda function definitely has permission to get objects from the S3 bucket, but S3 returns 403 errors for missing objects to requests without ListBucket permissions. See [this SO Q&A](https://stackoverflow.com/questions/19037664/how-do-i-have-an-s3-bucket-return-404-instead-of-403-for-a-key-that-does-not-e).
