### ISSUE TITLE
Auth not working for cloudflare

### ISSUE THREAD

**Issue by TheKnightCoder** [sst/ion#484]
I get the following error when trying to deploy sst Auth to cloudflare using `"sst": "^3.0.32",`

```
|  Creating    AuthAuthenticator sst:cloudflare:Worker → AuthAuthenticatorScript cloudflare:index:WorkerScript
|  Error       AuthAuthenticator sst:cloudflare:Worker → AuthAuthenticatorScript cloudflare:index:WorkerScript Error: Dynamic require of "node:util" is not supported
|  at worker.mjs:15:9
|  at worker.mjs:8316:23 in ../../../node_modules/.pnpm/openid-client@5.6.4/node_modules/openid-client/lib/issuer.js
|  at worker.mjs:21:51 in __require2
|  at worker.mjs:8648:19 in ../../../node_modules/.pnpm/openid-client@5.6.4/node_modules/openid-client/lib/index.js
|  at worker.mjs:21:51 in __require2
|  at worker.mjs:11361:28
|  (10021)

×  Failed
   AuthAuthenticator sst:cloudflare:Worker → AuthAuthenticatorScript cloudflare:index:WorkerScript
   Error: Dynamic require of "node:util" is not supported
   at worker.mjs:15:9
   at worker.mjs:8316:23 in ../../../node_modules/.pnpm/openid-client@5.6.4/node_modules/openid-client/lib/issuer.js
   at worker.mjs:21:51 in __require2
   at worker.mjs:8648:19 in ../../../node_modules/.pnpm/openid-client@5.6.4/node_modules/openid-client/lib/index.js
   at worker.mjs:21:51 in __require2
   at worker.mjs:11361:28
   (10021)
```

See src code here

Handler code

```
import { AuthHandler } from 'sst/auth'
import { sessions } from '../lib/sessions'
import { GoogleAdapter } from 'sst/auth/adapter'

const app = AuthHandler({
  session: sessions,
  providers: {
    google: GoogleAdapter({
      mode: 'oidc',
      clientID: process.env.GOOGLE_CLIENT_ID!,
    }),
  },
  callbacks: {
    auth: {
      async error(error, req) {
        return new Response('ok', {
          status: 302,
          headers: {
            Location: `auth/signin?error=unauthorized`,
          },
        })
      },
      async allowClient(clientID, redirect, req) {
        return true
      },
      async success(ctx, input, req) {
        const HOURS = 60 * 60 * 1000
        return ctx.session({
          type: 'user',
          expiresIn: 30 * 24 * HOURS,
          properties: {
            userId: 'user.data.userId',
            email: 'user.data.email',
          },
        })
      },
    },
  },
})

export default app
```

sst.config.ts

```
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: 'bootstrap-solidjs',
      removal: input?.stage === 'production' ? 'retain' : 'remove',
      home: 'cloudflare',
    }
  },
  async run() {
    const auth = new sst.cloudflare.Auth('Auth', {
      authenticator: {
        handler: 'apps/auth/api/session-create.ts',
      },
    })
  },
})
```

**Comment by itzcull** [comment]
I've got the same issues.

Trying to key KV values 
<img width="602" alt="Screenshot 2024-05-31 at 10 57 40 PM" src="https://github.com/sst/ion/assets/49985801/eb026a66-20b4-4afe-9b93-16c6c83fa4c5">
<img width="403" alt="Screenshot 2024-05-31 at 10 58 34 PM" src="https://github.com/sst/ion/assets/49985801/35c8cd4f-c639-4c7b-8aa5-020e61af8ea6">

**Comment by thdxr** [comment]
we haven't released sst.Auth yet and it seems like openid issuer has compatibility issues with cloudflare workers<br><br>going to close for now until we officially release
