### ISSUE TITLE
Error in sst dev Command: Could not resolve "path-to-regexp"

### ISSUE THREAD

**Issue by tothgBudapest** [sst/ion#710]
I'm encountering an error when running the sst dev command in my Next.js project using the Serverless Stack (SST). The error message indicates that the path-to-regexp module could not be resolved. Below are the details:

```
tothgergo@Toth-MacBook-Pro:~/Projects/demo-ion-nextjs|⇒  npm run dev

> demo-ion-nextjs@0.1.0 dev
> sst dev next dev

SST ❍ ion 0.0.542  ready!

➜  App:        demo-ion-nextjs
   Stage:      tothgergo
   Console:    https://console.sst.dev/local/demo-ion-nextjs/tothgergo

~  Deploying

|  Error       .sst/platform/src/components/cloudflare/remix.ts:3:29: Could not resolve "path-to-regexp"
```

Environment:

OS: macOS
Node.js version: [Your Node.js version]
npm version: [Your npm version]
SST version: 0.0.542

Expected Behavior:
The development server should start without any errors, and the application should be deployed successfully.

Actual Behavior:
The deployment fails with the error: "Could not resolve 'path-to-regexp'".

**Comment by ZachLegros** [comment]
+1

**Comment by thdxr** [comment]
does wiping the `.sst` folder fix this?

**Comment by jayair** [comment]
@tothgBudapest can I see your `sst.config.ts`? I'm confused why the Cloudlfare Remix component is involved here.

**Comment by balintant** [comment]
👋 

@jayair actually it is an issue with Yarn 4 it seems. No matter if `nodeLinker` is set to `node-modules` vs. `pnp`. We are using `yarn` through `corepack`. Using `pnpm` instead of `yarn` works just fine.

@thdxr no it doesn't make a difference. See ^

**Comment by jaapmvermeer** [comment]
I am also getting this error, please advise how to resolve

**Comment by balintant** [comment]
@jaapmvermeer what package manager do you use?

**Comment by jaapmvermeer** [comment]
npm@10.8.2
node v22.5.1

**Comment by balintant** [comment]
We didn't have the issue with `npm` or `pnpm`, only `yarn`. 🙁
Do you have the issue with the base configuration? Have you modified anything? (Can you share config / output?)

**Comment by jaapmvermeer** [comment]
thanks for looking into this. I am basically trying to follow the sst guide:
1. clone https://github.com/sst/monorepo-template
2. change app name to notes
3. npm install:

<img width="649" alt="image" src="https://github.com/user-attachments/assets/6d91c85c-98e5-4625-b22a-61fa68076a1c">

4.  make the changes to `infra/api.ts` ,` infra/storage.ts`, `packages/functions/src/api.ts`
5. update `sst.config.ts`
<img width="649" alt="image" src="https://github.com/user-attachments/assets/5d172ead-2874-4373-b901-ce0ca69e6021">

start the dev environment:
`npx sst dev`
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/124f0672-c52f-4520-8db7-8bcd2915ac5e">

then I try `npm audit fix`
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/8535041d-79dd-4216-a888-9a72daf8af56">

but give other error when starting `npx sst dev`

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/5afa8a25-1e3f-4575-a653-93a6dfb3094c">

**Comment by jaapmvermeer** [comment]
tried with 21.7.3 and have same results. I noticed another error in the log file:

> time=2024-08-08T08:52:39.834-04:00 level=ERROR msg="mutliplexer panic" err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 54 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/sst/ion/cmd/sst/mosaic/multiplexer.(*Multiplexer).Start.func2.1()\n\t/home/runner/work/ion/ion/cmd/sst/mosaic/multiplexer/multiplexer.go:99 +0x3f\npanic({0xb6d4920?, 0xc751a90?})\n\t/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:770 +0x132\ngithub.com/sst/ion/cmd/sst/mosaic/multiplexer.(*Multiplexer).draw(0xc000d5a600)\n\t/home/runner/work/ion/ion/cmd/sst/mosaic/multiplexer/draw.go:63 +0xc88\ngithub.com/sst/ion/cmd/sst/mosaic/multiplexer.(*Multiplexer).Start.func2(0xc000d5a600, {0xb9d0900, 0xc000d88280}, 0xc0010b1706)\n\t/home/runner/work/ion/ion/cmd/sst/mosaic/multiplexer/multiplexer.go:193 +0x8e7\ngithub.com/sst/ion/cmd/sst/mosaic/multiplexer.(*Multiplexer).Start(0xc000d5a600)\n\t/home/runner/work/ion/ion/cmd/sst/mosaic/multiplexer/multiplexer.go:304 +0xc5\nmain.CmdMosaic.func8()\n\t/home/runner/work/ion/ion/cmd/sst/mosaic.go:184 +0x57\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56\ncreated by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96\n"

Attaching the log file
[sst.log](https://github.com/user-attachments/files/16548450/sst.gh.log)

**Comment by jaapmvermeer** [comment]
I wiped my Mac and started with a clean install and I no longer haver the issue. Thanks for your time and assistance.

**Comment by jaapmvermeer** [comment]
I think I had some kind of conflict with node versions, versions of node modules or other packages.  I tried removing node, and all associated modules and libraries but after reinstalling I still had the issue so I decided to apply more drastic measure and using the Erase Assistant I reset my Mac to factory settings. This basically removes all content, settings, apps, user accounts and data. As I have all my files in the cloud, I only needed to reinstall some applications. This might not be the best approach for you but after a week of trying to find the underlying issue without success, this did the trick for me.

**Comment by huangyuan3h** [comment]
yes it happened when using yarn

**Comment by john20xdoe** [comment]
Possibly related? 
yarn might not be installing the dependencies inside .sst
https://github.com/evanw/esbuild/issues/3060

**Comment by thdxr** [comment]
the user's package manager is not responsible for anything inside `.sst` - we try to insure `.sst/platform/node_modules` is populated correctly.  can you check in there if that `path-to-regexp` package is missing?

**Comment by PVautour** [comment]
Here is the result of some testing on the base template:

Running `npm i path-to-regexp` from the root of my project resolves the error and gives:

```
SST 3.1.51  ready!

➜  App:        app-geo-ca-v2-1
   Stage:      pv
   Console:    https://console.sst.dev/local/app-geo-ca-v2-1/pv

~  Deploy

error: It looks like the Pulumi SDK has not been installed. Have you run n
pm install or yarn install?
|  Error
|  error reading from server: EOF

✕  Failed
   error reading from server: EOF


|  Error
```
If i remove the package from the root of my project I revert back to:

```
SST 3.1.51  ready!

➜  App:        app-geo-ca-v2-1
   Stage:      pv
   Console:    https://console.sst.dev/local/app-geo-ca-v2-1/pv

~  Deploy

|  Error       .sst/platform/src/components/cloudflare/remix.ts:3:29: Coul
d not resolve "path-to-regexp"
⠋  Deploying
```
There is currently no `node_modules/` under `my-app/.sst/platform`.

Going into `my-app/.sst/platform` and running `npm i` seems to resolve the issue.

The hello world app now deploys and functions as desired.

```
SST 3.1.51  ready!

➜  App:        xxx
   Stage:      yy
   Console:    https://console.sst.dev/local/xxx/yy

~  Deploy

|  Created     MyBucket sst:aws:Bucket
|  Created     MyBucket sst:aws:Bucket → MyBucketId random:index:RandomId
|  Created     MyApi sst:aws:Function → MyApiLogGroup aws:cloudwatch:LogGr
oup
|  Created     MyBucket sst:aws:Bucket → MyBucketBucket aws:s3:BucketV2 (1
.3s)
|  Created     MyApi sst:aws:Function (1.6s)
|  Created     MyBucket sst:aws:Bucket → MyBucketPublicAccessBlock aws:s3:
BucketPublicAccessBlock
|  Created     MyBucket sst:aws:Bucket → MyBucketCors aws:s3:BucketCorsCon
figurationV2
|  Created     MyBucket sst:aws:Bucket → MyBucketPolicy aws:s3:BucketPolic
y
|  Created     MyApi sst:aws:Function → MyApiRole aws:iam:Role
|  Created     MyApi sst:aws:Function → MyApiCode aws:s3:BucketObjectv2
|  Created     MyApi sst:aws:Function → MyApiFunction aws:lambda:Function
(16.2s)
|  Created     MyApi sst:aws:Function → MyApiUrl aws:lambda:FunctionUrl

✓  Complete
   api: https://xxx.lambda-url.ca-central-1.o
n.aws/
```
