### ISSUE TITLE
ReferenceError: crypto is not defined for 0.1.64

### ISSUE THREAD

**Issue by kwigley** [sst/ion#790]
after upgrading to 0.1.64 I get the following error on deploy (only in github/console builds)
```
Running program '/tmp/repo/.sst/platform/sst.config.1722392645972.mjs' failed with an unhandled exception:
ReferenceError: crypto is not defined
    at file:///tmp/repo/.sst/platform/src/components/aws/cdn.ts:404:16
    at /tmp/repo/.sst/platform/node_modules/@pulumi/output.ts:402:31
    at Generator.next (<anonymous>)
    at /tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
    at applyHelperAsync (/tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:244:12)
    at /tmp/repo/.sst/platform/node_modules/@pulumi/output.ts:316:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I think regression was added here https://github.com/sst/ion/commit/0b21b1ee29014b5c87ada2893af6eec79d56b1b2

**Comment by jackblanc** [comment]
+1

**Comment by ctrimm** [comment]
Also running into the same issue after an `sst upgrade` to `0.1.64`.

Downgraded to `0.1.62` for the time being. to resolve the issue. Didn't have time to verify @kwigley's fix.

**Comment by kwigley** [comment]
seems to be resolved after upgrading to `0.1.73`
