### ISSUE TITLE
MalformedPolicyDocument: Resource  must be in ARN format or "".

### ISSUE THREAD

**Issue by zdenham** [sst/ion#883]
Getting this error non-deterministically when creating a next.js site in a VPC linked to a postgres database.

It appears to have to do with the `AppDefaultRole` and the next.js function.

**Comment by zdenham** [comment]
This occurs every _other_ run actually 🤔

**Comment by fwang** [comment]
@zdenham just to double check on the function whose policy is causing this.. can share the terminal output?

**Comment by zdenham** [comment]
I ended up removing the database link which was the source of the issue, and configuring the database outside of SST. SST doesn't work on my local machine, so I wasn't able to debug locally this was occurring in CI, so digging into the .sst directory might be tricky.

Here is the config though, the database link is the source of the error, on sst version `3.0.42`

```
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: 'My-server',
      removal: input?.stage === 'production' ? 'retain' : 'remove',
      home: 'aws',
      providers: {
        cloudflare: {
          // this version is pinned because of: https://github.com/sst/ion/issues/876
          version: '5.24.1',
        },
        aws: {
          version: '6.49.1',
        },
      },
    };
  },
  async run() {
    const isProd = $app.stage === 'production';
    const isLocal = !isProd && $app.stage !== 'staging';

    const vpc = isProd ? new sst.aws.Vpc('MyVPC') : undefined;
    const nextVPCArg = vpc
      ? {
          securityGroups: [vpc.securityGroups[0]],
          privateSubnets: vpc.privateSubnets,
        }
      : undefined;

    if (isProd && !process.env.DATABASE_PASSWORD) {
      throw new Error('Missing environment variable: DATABASE_PASSWORD');
    }

    const database = isProd
      ? new sst.aws.Postgres('MyDB', {
          databaseName: 'Mydb',
          vpc,
          transform: {
            cluster: {
              // @ts-ignore - bug in aws see https://github.com/hashicorp/terraform-provider-aws/issues/31179
              manageMasterUserPassword: null,
              masterPassword: process.env.DATABASE_PASSWORD,
            },
          },
        })
      : null;

    const imagesBucket = new sst.aws.Bucket('MyImages', {
      public: true,
    });

    const cdnDomain = isLocal
      ? undefined
      : {
          name: isProd ? 'cdn.My-site.io' : 'staging-cdn.My-site.io',
          dns: sst.cloudflare.dns(),
        };

    new sst.aws.Cdn('MyCDN', {
      origins: [
        {
          domainName: imagesBucket.domain,
          originId: 'my-bucket-origin',
        },
      ],
      domain: cdnDomain,
      defaultCacheBehavior: {
        targetOriginId: 'my-bucket-origin',
        allowedMethods: ['GET', 'HEAD', 'OPTIONS'],
        cachedMethods: ['GET', 'HEAD', 'OPTIONS'],
        forwardedValues: {
          queryString: true,
          cookies: { forward: 'none' },
        },
        viewerProtocolPolicy: 'redirect-to-https',
      },
    });

    const link: SsrSiteArgs['link'] = [
      database, // separate lines to make commenting out easier THIS IS THE PROBLEM!!!!
      imagesBucket,
    ].filter(Boolean);

    const domain = isLocal
      ? undefined
      : {
          name: isProd ? 'api.My-site.io' : 'staging-api.My-site.io',
          dns: sst.cloudflare.dns(),
        };

    new sst.aws.Nextjs('MyServerApp', {
      link: link,
      // @ts-ignore - sst types not updated
      // vpc: nextVPCArg,
      environment: constructEnv(),
      domain,
      transform: {
        server: {
          timeout: '300 seconds',
        },
      },
      warm: isProd ? 2 : 0,
    });
  },
});
```

**Comment by thdxr** [comment]
how come sst doesn't work on your machine?

**Comment by zdenham** [comment]
I'm not sure, it crashes non-deterministically on longer jobs, sometimes dev works but it almost always crashes on deploy with the following:

```
|  Log         assertion failed [arm_interval().contains(address)]: code fragment does not contain the given arm address
|  Log         (CodeFragmentMetadata.cpp:48 instruction_extents_for_arm_address)
```
Couldn't find this code anywhere. I think it could be my machine though, it worked fine on an old intel chip, but when I upgraded to M3 it started crashing. I have a feeling it has something to do with outdated binaries and Rosetta 2 translation to run on Arm64. I had ported node binaries from the old device, which I now regret.

I have a TODO to hard reset my machine and see if the issue persists, I would imagine not SST's fault.

**Comment by rbasto1** [comment]
I'm facing the same issue: sst fails every other run due to an empty-string resource. I've inspected the `statements` as suggested by @fwang and this is the culprit:
```
  {
    actions: [ 'secretsmanager:GetSecretValue' ],
    conditions: [],
    effect: 'Allow',
    notActions: [],
    notPrincipals: [],
    notResources: [],
    principals: [],
    resources: [ '' ],
    sid: ''
  },
```
What I think happened is that I used to have `manageMasterUserPassword: true` but since I have to enable cross-region backup replication I had to disable it and I'm specifying the masterPassword directly now. I think sst still thinks that the app needs access to secrets manager, but in reality there is no resource there to grant access to.

But the real issue is that, when sst actually succeeds in deploying, the default role for my functions doesn't have the inline policies that are needed, so most operations fail.

Any idea what I have to do to fix that? I tried removing the .sst folder and start anew but then this new error (below) started to appear and I don't want to dive into this rabbit role right now...
```
|  TypeError: pulumi.runtime.invokeOutput is not a function
|      at getRegionOutput (.sst/platform/node_modules/@pulumi/getRegion.ts:93:27)
|      at normalizeRegion (file://.sst/platform/src/components/aws/function.ts:1022:14)
|      at new _Function (file://.sst/platform/src/components/aws/function.ts:954:20)
[...]
```
