### ISSUE TITLE
BUG : Error when requesting a Magic Link

### ISSUE THREAD

**Issue by TheUncharted** [sst/ion#967]
When I request the magic link with auth, I get this error 

 +1.483s     TypeError: response.headers.entries is not a function
|  +1.483s         at Object.forward (/home/uncharted/projects/myapp/node_modules/sst/dist/auth/handler.js:120:104)
|  +1.483s         at <anonymous> (/home/uncharted/projects/myapp/node_modules/sst/dist/auth/adapter/link.js:15:30)
|  +1.483s         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|  +1.483s         at dispatch (/home/uncharted/projects/myapp/node_modules/hono/dist/compose.js:29:17)
|  +1.483s         at <anonymous> (/home/uncharted/projects/myapp/node_modules/sst/dist/auth/handler.js:194:13)
|  +1.483s         at dispatch (/home/uncharted/projects/myapp/node_modules/hono/dist/compose.js:29:17)
|  +1.483s         at <anonymous> (/home/uncharted/projects/myapp/node_modules/sst/dist/auth/handler.js:188:9)
|  +1.483s         at dispatch (/home/uncharted/projects/myapp/node_modules/hono/dist/compose.js:29:17)
|  +1.483s         at <anonymous> (/home/uncharted/projects/myapp/node_modules/hono/dist/hono-base.js:200:25)
|  +1.483s         at <anonymous> (/home/uncharted/projects/myapp/node_modules/hono/dist/adapter/aws-lambda/handler.js:62:17)
|  Done        took +1.729s

**Comment by thdxr** [comment]
what are you returning from the `onLink` callback?

**Comment by TheUncharted** [comment]
good question I was still return a object like before in SST 2

```
  return {
          statusCode: 302,
          headers: {
            location: `${process.env.FRONTEND_URL}/sign-in?emailSent=true`,
          },
        };
```

but now i get this error after clicking on the link

`The browser was in an unknown state. This could be because certain cookies expired or the browser was switched in the middle of an authentication flow`

I noticed that the url is not using the domain but the generated url if I compare to the code or google adapter flow 

https://xxxxx.lambda-url.us-east-1.on.aws/link/callback?token=eyJhbGciOiJSUxxxxxxxxxxxxxx

**Comment by thdxr** [comment]
so this is how we're building the url

```
      const url = new URL(new URL(c.req.url).origin);
      url.pathname = `/${ctx.name}/callback`;
      for (const key of url.searchParams.keys()) {
        url.searchParams.delete(key);
      }
      url.searchParams.set("token", token);
```

i'm wondering if `c.req.url` doesn't give you the right hting - maybe i need to get it from the host header? how are you assigning a custom domain btw - are you putting it in front of an sst.aws.Router?

**Comment by TheUncharted** [comment]
I created 2 routers

```typescript
export const apiRouter = new sst.aws.Router("Router", {
  domain: {
    name: `api.${domain}`,
    dns: sst.aws.dns(),
  },

  routes: {
    "/*": api.url,
  },
});

export const authRouter = new sst.aws.Router("AuthRouter", {
  domain: {
    name: `auth.${domain}`,
    dns: sst.aws.dns(),
  },

  routes: {
    "/*": auth.url.apply((url) => {
      return url!;
    }),
  },
});

```

**Comment by thdxr** [comment]
no that is correct, this is likely a bug - a workaround right now is to parse the url and fix the domain before sending it out on the onLink callback but we will fix it

**Comment by TheUncharted** [comment]
yes that's what i'm actually doing it work
