### ISSUE TITLE
Impossible to use pre-existing role for ApiGatewayV1 routes

### ISSUE THREAD

**Issue by antoine-js** [sst/ion#987]
For ApiGatewayV2, it works:

```ts
const api = new sst.aws.ApiGatewayV2("MyApi");

api.route("GET /", {
  handler: "index.test",
  role: `arn:aws:iam::${accountId}:role/my-role`,
  memory: "256 MB",
  timeout: "30 seconds",
});
```

For ApiGatewayV1, it does not work:

```ts
const api = new sst.aws.ApiGatewayV1("MyApi");

api.route("GET /", {
  handler: "index.test",
  role: `arn:aws:iam::${accountId}:role/my-role`,
  memory: "256 MB",
  timeout: "30 seconds",
});
```

Error:
```
✕  Failed
   Error: "nodes.role" is not available when a pre-existing role is used.

       at Object.get role [as role] (file:///my-project/.sst/platform/src/components/aws/function.ts:1596
:17)
       at /my-project/.sst/platform/node_modules/@pulumi/output.ts:758:57

       at Array.some (<anonymous>)

       at impl (/my-project/.sst/platform/node_modules/@pulumi/output.ts:758:37)

       at containsUnknowns (/my-project/.sst/platform/node_modules/@pulumi/output.ts:743:12)

       at /my-project/.sst/platform/node_modules/@pulumi/output.ts:180:84

       at processTicksAndRejections (node:internal/process/task_queues:95:5)

       at async Promise.all (index 2)
```

**Comment by jonathanPretre** [comment]
Actually, we are facing the same issue in my company. It is the last blocker we have before to move all our stack to SST. I hope this issue will find a solution 🤞

**Comment by fwang** [comment]
@antoine-js sorry about the delay.

i'm not getting the error w/ ur above code:
```ts
const api = new sst.aws.ApiGatewayV1("MyApi");

api.route("GET /", {
  handler: "index.test",
  role: `arn-of-a-role-used-by-another-lambda`,
});
```
I could successfully deploy.

Are you manually calling `.nodes.role`? /cc @jonathanPretre

**Comment by antoine-js** [comment]
Hi @fwang,

I retried with my current version of SST (3.0.73) and still didnt work. But I tried upgrading to latest version (3.1.35) and it worked!

So I guess it was fixed indirectly.

I still wonder if my PR is worth checking as it should prevent any potential issue like this in the future by referencing the role used when not creating one. But other than that, we can close this issue.

**Comment by fwang** [comment]
Hye @antoine-js thanks for the update.

Currently the thinking is if something was not created by the component, `.nodes.xxxx` will throw an error. We do this in multiple places.

I can see the flip side of referencing instead of throw.

I don't have enough conviction leaning one way or another. For now i'm going to leave it as in. But if more ppl r running into similar issues, I'm up for changing the behavior.
